targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          outputDirectory: /lib/repository
          assetsPath: /lib/graphql/**