name: test_things
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0 # This package helps in creation of data collection forms in Flutter by removing the boilerplate needed to build a form, validate fields, react to changes, and collect final user input.
  flutter_hooks:
  flutter_svg: ^1.1.6
  flutter_typeahead: ^4.1.1
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.4.0 #Form Builder Validators provide a convenient way of validating data entered into any Flutter FormField. It offers common validation rules out of the box
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_animate: ^2.0.1
  universal_io:
  device_preview: ^1.1.0
  uni_links: ^0.5.1
  flutter_adaptive_scaffold: ^0.0.8
  go_router: ^5.2.1
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  graphql_codegen: ^0.11.2
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/launcher/
    - assets/tutorial/